// Code generated by hack/generate_podspec_equal.py. DO NOT EDIT.
package workloadmanager

import (
	corev1 "k8s.io/api/core/v1"
	"reflect"
)

func PodSpecEqual(a, b corev1.PodSpec) bool {
	if len(a.Volumes) != len(b.Volumes) { return false }
	for i := range a.Volumes {
		if !VolumeEqual(a.Volumes[i], b.Volumes[i]) { return false }
	}
	if len(a.InitContainers) != len(b.InitContainers) { return false }
	for i := range a.InitContainers {
		if !ContainerEqual(a.InitContainers[i], b.InitContainers[i]) { return false }
	}
	if len(a.Containers) != len(b.Containers) { return false }
	for i := range a.Containers {
		if !ContainerEqual(a.Containers[i], b.Containers[i]) { return false }
	}
	if len(a.EphemeralContainers) != len(b.EphemeralContainers) { return false }
	for i := range a.EphemeralContainers {
		if !EphemeralContainerEqual(a.EphemeralContainers[i], b.EphemeralContainers[i]) { return false }
	}
	if a.RestartPolicy != b.RestartPolicy { return false }
	if (a.TerminationGracePeriodSeconds == nil) != (b.TerminationGracePeriodSeconds == nil) { return false }
	if a.TerminationGracePeriodSeconds != nil {
		if *a.TerminationGracePeriodSeconds != *b.TerminationGracePeriodSeconds { return false }
	}
	if (a.ActiveDeadlineSeconds == nil) != (b.ActiveDeadlineSeconds == nil) { return false }
	if a.ActiveDeadlineSeconds != nil {
		if *a.ActiveDeadlineSeconds != *b.ActiveDeadlineSeconds { return false }
	}
	if a.DNSPolicy != b.DNSPolicy { return false }
	if len(a.NodeSelector) != len(b.NodeSelector) { return false }
	for k, v := range a.NodeSelector {
		if v2, ok := b.NodeSelector[k]; !ok || v != v2 { return false }
	}
	if a.ServiceAccountName != b.ServiceAccountName { return false }
	if a.DeprecatedServiceAccount != b.DeprecatedServiceAccount { return false }
	if (a.AutomountServiceAccountToken == nil) != (b.AutomountServiceAccountToken == nil) { return false }
	if a.AutomountServiceAccountToken != nil {
		if *a.AutomountServiceAccountToken != *b.AutomountServiceAccountToken { return false }
	}
	if a.NodeName != b.NodeName { return false }
	if a.HostNetwork != b.HostNetwork { return false }
	if a.HostPID != b.HostPID { return false }
	if a.HostIPC != b.HostIPC { return false }
	if (a.ShareProcessNamespace == nil) != (b.ShareProcessNamespace == nil) { return false }
	if a.ShareProcessNamespace != nil {
		if *a.ShareProcessNamespace != *b.ShareProcessNamespace { return false }
	}
	if (a.SecurityContext == nil) != (b.SecurityContext == nil) { return false }
	if a.SecurityContext != nil {
		if !PodSecurityContextEqual(*a.SecurityContext, *b.SecurityContext) { return false }
	}
	if len(a.ImagePullSecrets) != len(b.ImagePullSecrets) { return false }
	for i := range a.ImagePullSecrets {
		if !LocalObjectReferenceEqual(a.ImagePullSecrets[i], b.ImagePullSecrets[i]) { return false }
	}
	if a.Hostname != b.Hostname { return false }
	if a.Subdomain != b.Subdomain { return false }
	if (a.Affinity == nil) != (b.Affinity == nil) { return false }
	if a.Affinity != nil {
		if !AffinityEqual(*a.Affinity, *b.Affinity) { return false }
	}
	if a.SchedulerName != b.SchedulerName { return false }
	if len(a.Tolerations) != len(b.Tolerations) { return false }
	for i := range a.Tolerations {
		if !TolerationEqual(a.Tolerations[i], b.Tolerations[i]) { return false }
	}
	if len(a.HostAliases) != len(b.HostAliases) { return false }
	for i := range a.HostAliases {
		if !HostAliasEqual(a.HostAliases[i], b.HostAliases[i]) { return false }
	}
	if a.PriorityClassName != b.PriorityClassName { return false }
	if (a.Priority == nil) != (b.Priority == nil) { return false }
	if a.Priority != nil {
		if *a.Priority != *b.Priority { return false }
	}
	if (a.DNSConfig == nil) != (b.DNSConfig == nil) { return false }
	if a.DNSConfig != nil {
		if !PodDNSConfigEqual(*a.DNSConfig, *b.DNSConfig) { return false }
	}
	if len(a.ReadinessGates) != len(b.ReadinessGates) { return false }
	for i := range a.ReadinessGates {
		if !PodReadinessGateEqual(a.ReadinessGates[i], b.ReadinessGates[i]) { return false }
	}
	if (a.RuntimeClassName == nil) != (b.RuntimeClassName == nil) { return false }
	if a.RuntimeClassName != nil {
		if *a.RuntimeClassName != *b.RuntimeClassName { return false }
	}
	if (a.EnableServiceLinks == nil) != (b.EnableServiceLinks == nil) { return false }
	if a.EnableServiceLinks != nil {
		if *a.EnableServiceLinks != *b.EnableServiceLinks { return false }
	}
	if (a.PreemptionPolicy == nil) != (b.PreemptionPolicy == nil) { return false }
	if a.PreemptionPolicy != nil {
		if *a.PreemptionPolicy != *b.PreemptionPolicy { return false }
	}
	if !ResourceListEqual(a.Overhead, b.Overhead) { return false }
	if len(a.TopologySpreadConstraints) != len(b.TopologySpreadConstraints) { return false }
	for i := range a.TopologySpreadConstraints {
		if !TopologySpreadConstraintEqual(a.TopologySpreadConstraints[i], b.TopologySpreadConstraints[i]) { return false }
	}
	if (a.SetHostnameAsFQDN == nil) != (b.SetHostnameAsFQDN == nil) { return false }
	if a.SetHostnameAsFQDN != nil {
		if *a.SetHostnameAsFQDN != *b.SetHostnameAsFQDN { return false }
	}
	if (a.OS == nil) != (b.OS == nil) { return false }
	if a.OS != nil {
		if !PodOSEqual(*a.OS, *b.OS) { return false }
	}
	if (a.HostUsers == nil) != (b.HostUsers == nil) { return false }
	if a.HostUsers != nil {
		if *a.HostUsers != *b.HostUsers { return false }
	}
	if len(a.SchedulingGates) != len(b.SchedulingGates) { return false }
	for i := range a.SchedulingGates {
		if !PodSchedulingGateEqual(a.SchedulingGates[i], b.SchedulingGates[i]) { return false }
	}
	if len(a.ResourceClaims) != len(b.ResourceClaims) { return false }
	for i := range a.ResourceClaims {
		if !PodResourceClaimEqual(a.ResourceClaims[i], b.ResourceClaims[i]) { return false }
	}
	if (a.Resources == nil) != (b.Resources == nil) { return false }
	if a.Resources != nil {
		if !ResourceRequirementsEqual(*a.Resources, *b.Resources) { return false }
	}
	if (a.HostnameOverride == nil) != (b.HostnameOverride == nil) { return false }
	if a.HostnameOverride != nil {
		if *a.HostnameOverride != *b.HostnameOverride { return false }
	}
	return true
}

func VolumeEqual(a, b corev1.Volume) bool {
	if a.Name != b.Name { return false }
	return true
}

func ContainerEqual(a, b corev1.Container) bool {
	if a.Name != b.Name { return false }
	if a.Image != b.Image { return false }
	if len(a.Command) != len(b.Command) { return false }
	for i := range a.Command {
		if a.Command[i] != b.Command[i] { return false }
	}
	if len(a.Args) != len(b.Args) { return false }
	for i := range a.Args {
		if a.Args[i] != b.Args[i] { return false }
	}
	if a.WorkingDir != b.WorkingDir { return false }
	if len(a.Ports) != len(b.Ports) { return false }
	for i := range a.Ports {
		if !ContainerPortEqual(a.Ports[i], b.Ports[i]) { return false }
	}
	if len(a.EnvFrom) != len(b.EnvFrom) { return false }
	for i := range a.EnvFrom {
		if !EnvFromSourceEqual(a.EnvFrom[i], b.EnvFrom[i]) { return false }
	}
	if len(a.Env) != len(b.Env) { return false }
	for i := range a.Env {
		if !EnvVarEqual(a.Env[i], b.Env[i]) { return false }
	}
	if !ResourceRequirementsEqual(a.Resources, b.Resources) { return false }
	if len(a.ResizePolicy) != len(b.ResizePolicy) { return false }
	for i := range a.ResizePolicy {
		if !ContainerResizePolicyEqual(a.ResizePolicy[i], b.ResizePolicy[i]) { return false }
	}
	if (a.RestartPolicy == nil) != (b.RestartPolicy == nil) { return false }
	if a.RestartPolicy != nil {
		if *a.RestartPolicy != *b.RestartPolicy { return false }
	}
	if len(a.RestartPolicyRules) != len(b.RestartPolicyRules) { return false }
	for i := range a.RestartPolicyRules {
		if !ContainerRestartRuleEqual(a.RestartPolicyRules[i], b.RestartPolicyRules[i]) { return false }
	}
	if len(a.VolumeMounts) != len(b.VolumeMounts) { return false }
	for i := range a.VolumeMounts {
		if !VolumeMountEqual(a.VolumeMounts[i], b.VolumeMounts[i]) { return false }
	}
	if len(a.VolumeDevices) != len(b.VolumeDevices) { return false }
	for i := range a.VolumeDevices {
		if !VolumeDeviceEqual(a.VolumeDevices[i], b.VolumeDevices[i]) { return false }
	}
	if (a.LivenessProbe == nil) != (b.LivenessProbe == nil) { return false }
	if a.LivenessProbe != nil {
		if !ProbeEqual(*a.LivenessProbe, *b.LivenessProbe) { return false }
	}
	if (a.ReadinessProbe == nil) != (b.ReadinessProbe == nil) { return false }
	if a.ReadinessProbe != nil {
		if !ProbeEqual(*a.ReadinessProbe, *b.ReadinessProbe) { return false }
	}
	if (a.StartupProbe == nil) != (b.StartupProbe == nil) { return false }
	if a.StartupProbe != nil {
		if !ProbeEqual(*a.StartupProbe, *b.StartupProbe) { return false }
	}
	if (a.Lifecycle == nil) != (b.Lifecycle == nil) { return false }
	if a.Lifecycle != nil {
		if !LifecycleEqual(*a.Lifecycle, *b.Lifecycle) { return false }
	}
	if a.TerminationMessagePath != b.TerminationMessagePath { return false }
	if a.TerminationMessagePolicy != b.TerminationMessagePolicy { return false }
	if a.ImagePullPolicy != b.ImagePullPolicy { return false }
	if (a.SecurityContext == nil) != (b.SecurityContext == nil) { return false }
	if a.SecurityContext != nil {
		if !SecurityContextEqual(*a.SecurityContext, *b.SecurityContext) { return false }
	}
	if a.Stdin != b.Stdin { return false }
	if a.StdinOnce != b.StdinOnce { return false }
	if a.TTY != b.TTY { return false }
	return true
}

func EphemeralContainerEqual(a, b corev1.EphemeralContainer) bool {
	if a.TargetContainerName != b.TargetContainerName { return false }
	return true
}

func PodSecurityContextEqual(a, b corev1.PodSecurityContext) bool {
	if (a.SELinuxOptions == nil) != (b.SELinuxOptions == nil) { return false }
	if a.SELinuxOptions != nil {
		if !SELinuxOptionsEqual(*a.SELinuxOptions, *b.SELinuxOptions) { return false }
	}
	if (a.WindowsOptions == nil) != (b.WindowsOptions == nil) { return false }
	if a.WindowsOptions != nil {
		if !WindowsSecurityContextOptionsEqual(*a.WindowsOptions, *b.WindowsOptions) { return false }
	}
	if (a.RunAsUser == nil) != (b.RunAsUser == nil) { return false }
	if a.RunAsUser != nil {
		if *a.RunAsUser != *b.RunAsUser { return false }
	}
	if (a.RunAsGroup == nil) != (b.RunAsGroup == nil) { return false }
	if a.RunAsGroup != nil {
		if *a.RunAsGroup != *b.RunAsGroup { return false }
	}
	if (a.RunAsNonRoot == nil) != (b.RunAsNonRoot == nil) { return false }
	if a.RunAsNonRoot != nil {
		if *a.RunAsNonRoot != *b.RunAsNonRoot { return false }
	}
	if len(a.SupplementalGroups) != len(b.SupplementalGroups) { return false }
	for i := range a.SupplementalGroups {
		if a.SupplementalGroups[i] != b.SupplementalGroups[i] { return false }
	}
	if (a.SupplementalGroupsPolicy == nil) != (b.SupplementalGroupsPolicy == nil) { return false }
	if a.SupplementalGroupsPolicy != nil {
		if *a.SupplementalGroupsPolicy != *b.SupplementalGroupsPolicy { return false }
	}
	if (a.FSGroup == nil) != (b.FSGroup == nil) { return false }
	if a.FSGroup != nil {
		if *a.FSGroup != *b.FSGroup { return false }
	}
	if len(a.Sysctls) != len(b.Sysctls) { return false }
	for i := range a.Sysctls {
		if !SysctlEqual(a.Sysctls[i], b.Sysctls[i]) { return false }
	}
	if (a.FSGroupChangePolicy == nil) != (b.FSGroupChangePolicy == nil) { return false }
	if a.FSGroupChangePolicy != nil {
		if *a.FSGroupChangePolicy != *b.FSGroupChangePolicy { return false }
	}
	if (a.SeccompProfile == nil) != (b.SeccompProfile == nil) { return false }
	if a.SeccompProfile != nil {
		if !SeccompProfileEqual(*a.SeccompProfile, *b.SeccompProfile) { return false }
	}
	if (a.AppArmorProfile == nil) != (b.AppArmorProfile == nil) { return false }
	if a.AppArmorProfile != nil {
		if !AppArmorProfileEqual(*a.AppArmorProfile, *b.AppArmorProfile) { return false }
	}
	if (a.SELinuxChangePolicy == nil) != (b.SELinuxChangePolicy == nil) { return false }
	if a.SELinuxChangePolicy != nil {
		if *a.SELinuxChangePolicy != *b.SELinuxChangePolicy { return false }
	}
	return true
}

func LocalObjectReferenceEqual(a, b corev1.LocalObjectReference) bool {
	if a.Name != b.Name { return false }
	return true
}

func AffinityEqual(a, b corev1.Affinity) bool {
	if (a.NodeAffinity == nil) != (b.NodeAffinity == nil) { return false }
	if a.NodeAffinity != nil {
		if !NodeAffinityEqual(*a.NodeAffinity, *b.NodeAffinity) { return false }
	}
	if (a.PodAffinity == nil) != (b.PodAffinity == nil) { return false }
	if a.PodAffinity != nil {
		if !PodAffinityEqual(*a.PodAffinity, *b.PodAffinity) { return false }
	}
	if (a.PodAntiAffinity == nil) != (b.PodAntiAffinity == nil) { return false }
	if a.PodAntiAffinity != nil {
		if !PodAntiAffinityEqual(*a.PodAntiAffinity, *b.PodAntiAffinity) { return false }
	}
	return true
}

func TolerationEqual(a, b corev1.Toleration) bool {
	if a.Key != b.Key { return false }
	if a.Operator != b.Operator { return false }
	if a.Value != b.Value { return false }
	if a.Effect != b.Effect { return false }
	if (a.TolerationSeconds == nil) != (b.TolerationSeconds == nil) { return false }
	if a.TolerationSeconds != nil {
		if *a.TolerationSeconds != *b.TolerationSeconds { return false }
	}
	return true
}

func HostAliasEqual(a, b corev1.HostAlias) bool {
	if a.IP != b.IP { return false }
	if len(a.Hostnames) != len(b.Hostnames) { return false }
	for i := range a.Hostnames {
		if a.Hostnames[i] != b.Hostnames[i] { return false }
	}
	return true
}

func PodDNSConfigEqual(a, b corev1.PodDNSConfig) bool {
	if len(a.Nameservers) != len(b.Nameservers) { return false }
	for i := range a.Nameservers {
		if a.Nameservers[i] != b.Nameservers[i] { return false }
	}
	if len(a.Searches) != len(b.Searches) { return false }
	for i := range a.Searches {
		if a.Searches[i] != b.Searches[i] { return false }
	}
	if len(a.Options) != len(b.Options) { return false }
	for i := range a.Options {
		if !PodDNSConfigOptionEqual(a.Options[i], b.Options[i]) { return false }
	}
	return true
}

func PodReadinessGateEqual(a, b corev1.PodReadinessGate) bool {
	if a.ConditionType != b.ConditionType { return false }
	return true
}

func ResourceListEqual(a, b corev1.ResourceList) bool {
	if len(a) != len(b) { return false }
	for k, v := range a {
		if v2, ok := b[k]; !ok || !v.Equal(v2) { return false }
	}
	return true
}

func TopologySpreadConstraintEqual(a, b corev1.TopologySpreadConstraint) bool {
	if a.MaxSkew != b.MaxSkew { return false }
	if a.TopologyKey != b.TopologyKey { return false }
	if a.WhenUnsatisfiable != b.WhenUnsatisfiable { return false }
	if (a.LabelSelector == nil) != (b.LabelSelector == nil) { return false }
	if a.LabelSelector != nil {
		if !reflect.DeepEqual(*a.LabelSelector, *b.LabelSelector) { return false }
	}
	if (a.MinDomains == nil) != (b.MinDomains == nil) { return false }
	if a.MinDomains != nil {
		if *a.MinDomains != *b.MinDomains { return false }
	}
	if (a.NodeAffinityPolicy == nil) != (b.NodeAffinityPolicy == nil) { return false }
	if a.NodeAffinityPolicy != nil {
		if *a.NodeAffinityPolicy != *b.NodeAffinityPolicy { return false }
	}
	if (a.NodeTaintsPolicy == nil) != (b.NodeTaintsPolicy == nil) { return false }
	if a.NodeTaintsPolicy != nil {
		if *a.NodeTaintsPolicy != *b.NodeTaintsPolicy { return false }
	}
	if len(a.MatchLabelKeys) != len(b.MatchLabelKeys) { return false }
	for i := range a.MatchLabelKeys {
		if a.MatchLabelKeys[i] != b.MatchLabelKeys[i] { return false }
	}
	return true
}

func PodOSEqual(a, b corev1.PodOS) bool {
	if a.Name != b.Name { return false }
	return true
}

func PodSchedulingGateEqual(a, b corev1.PodSchedulingGate) bool {
	if a.Name != b.Name { return false }
	return true
}

func PodResourceClaimEqual(a, b corev1.PodResourceClaim) bool {
	if a.Name != b.Name { return false }
	if (a.ResourceClaimName == nil) != (b.ResourceClaimName == nil) { return false }
	if a.ResourceClaimName != nil {
		if *a.ResourceClaimName != *b.ResourceClaimName { return false }
	}
	if (a.ResourceClaimTemplateName == nil) != (b.ResourceClaimTemplateName == nil) { return false }
	if a.ResourceClaimTemplateName != nil {
		if *a.ResourceClaimTemplateName != *b.ResourceClaimTemplateName { return false }
	}
	return true
}

func ResourceRequirementsEqual(a, b corev1.ResourceRequirements) bool {
	if !ResourceListEqual(a.Limits, b.Limits) { return false }
	if !ResourceListEqual(a.Requests, b.Requests) { return false }
	if len(a.Claims) != len(b.Claims) { return false }
	for i := range a.Claims {
		if !ResourceClaimEqual(a.Claims[i], b.Claims[i]) { return false }
	}
	return true
}

func ContainerPortEqual(a, b corev1.ContainerPort) bool {
	if a.Name != b.Name { return false }
	if a.HostPort != b.HostPort { return false }
	if a.ContainerPort != b.ContainerPort { return false }
	if a.Protocol != b.Protocol { return false }
	if a.HostIP != b.HostIP { return false }
	return true
}

func EnvFromSourceEqual(a, b corev1.EnvFromSource) bool {
	if a.Prefix != b.Prefix { return false }
	if (a.ConfigMapRef == nil) != (b.ConfigMapRef == nil) { return false }
	if a.ConfigMapRef != nil {
		if !ConfigMapEnvSourceEqual(*a.ConfigMapRef, *b.ConfigMapRef) { return false }
	}
	if (a.SecretRef == nil) != (b.SecretRef == nil) { return false }
	if a.SecretRef != nil {
		if !SecretEnvSourceEqual(*a.SecretRef, *b.SecretRef) { return false }
	}
	return true
}

func EnvVarEqual(a, b corev1.EnvVar) bool {
	if a.Name != b.Name { return false }
	if a.Value != b.Value { return false }
	if (a.ValueFrom == nil) != (b.ValueFrom == nil) { return false }
	if a.ValueFrom != nil {
		if !EnvVarSourceEqual(*a.ValueFrom, *b.ValueFrom) { return false }
	}
	return true
}

func ContainerResizePolicyEqual(a, b corev1.ContainerResizePolicy) bool {
	if a.ResourceName != b.ResourceName { return false }
	if a.RestartPolicy != b.RestartPolicy { return false }
	return true
}

func ContainerRestartRuleEqual(a, b corev1.ContainerRestartRule) bool {
	if a.Action != b.Action { return false }
	if (a.ExitCodes == nil) != (b.ExitCodes == nil) { return false }
	if a.ExitCodes != nil {
		if !ContainerRestartRuleOnExitCodesEqual(*a.ExitCodes, *b.ExitCodes) { return false }
	}
	return true
}

func VolumeMountEqual(a, b corev1.VolumeMount) bool {
	if a.Name != b.Name { return false }
	if a.ReadOnly != b.ReadOnly { return false }
	if (a.RecursiveReadOnly == nil) != (b.RecursiveReadOnly == nil) { return false }
	if a.RecursiveReadOnly != nil {
		if *a.RecursiveReadOnly != *b.RecursiveReadOnly { return false }
	}
	if a.MountPath != b.MountPath { return false }
	if a.SubPath != b.SubPath { return false }
	if (a.MountPropagation == nil) != (b.MountPropagation == nil) { return false }
	if a.MountPropagation != nil {
		if *a.MountPropagation != *b.MountPropagation { return false }
	}
	if a.SubPathExpr != b.SubPathExpr { return false }
	return true
}

func VolumeDeviceEqual(a, b corev1.VolumeDevice) bool {
	if a.Name != b.Name { return false }
	if a.DevicePath != b.DevicePath { return false }
	return true
}

func ProbeEqual(a, b corev1.Probe) bool {
	if a.InitialDelaySeconds != b.InitialDelaySeconds { return false }
	if a.TimeoutSeconds != b.TimeoutSeconds { return false }
	if a.PeriodSeconds != b.PeriodSeconds { return false }
	if a.SuccessThreshold != b.SuccessThreshold { return false }
	if a.FailureThreshold != b.FailureThreshold { return false }
	if (a.TerminationGracePeriodSeconds == nil) != (b.TerminationGracePeriodSeconds == nil) { return false }
	if a.TerminationGracePeriodSeconds != nil {
		if *a.TerminationGracePeriodSeconds != *b.TerminationGracePeriodSeconds { return false }
	}
	return true
}

func LifecycleEqual(a, b corev1.Lifecycle) bool {
	if (a.PostStart == nil) != (b.PostStart == nil) { return false }
	if a.PostStart != nil {
		if !LifecycleHandlerEqual(*a.PostStart, *b.PostStart) { return false }
	}
	if (a.PreStop == nil) != (b.PreStop == nil) { return false }
	if a.PreStop != nil {
		if !LifecycleHandlerEqual(*a.PreStop, *b.PreStop) { return false }
	}
	if (a.StopSignal == nil) != (b.StopSignal == nil) { return false }
	if a.StopSignal != nil {
		if *a.StopSignal != *b.StopSignal { return false }
	}
	return true
}

func SecurityContextEqual(a, b corev1.SecurityContext) bool {
	if (a.Capabilities == nil) != (b.Capabilities == nil) { return false }
	if a.Capabilities != nil {
		if !CapabilitiesEqual(*a.Capabilities, *b.Capabilities) { return false }
	}
	if (a.Privileged == nil) != (b.Privileged == nil) { return false }
	if a.Privileged != nil {
		if *a.Privileged != *b.Privileged { return false }
	}
	if (a.SELinuxOptions == nil) != (b.SELinuxOptions == nil) { return false }
	if a.SELinuxOptions != nil {
		if !SELinuxOptionsEqual(*a.SELinuxOptions, *b.SELinuxOptions) { return false }
	}
	if (a.WindowsOptions == nil) != (b.WindowsOptions == nil) { return false }
	if a.WindowsOptions != nil {
		if !WindowsSecurityContextOptionsEqual(*a.WindowsOptions, *b.WindowsOptions) { return false }
	}
	if (a.RunAsUser == nil) != (b.RunAsUser == nil) { return false }
	if a.RunAsUser != nil {
		if *a.RunAsUser != *b.RunAsUser { return false }
	}
	if (a.RunAsGroup == nil) != (b.RunAsGroup == nil) { return false }
	if a.RunAsGroup != nil {
		if *a.RunAsGroup != *b.RunAsGroup { return false }
	}
	if (a.RunAsNonRoot == nil) != (b.RunAsNonRoot == nil) { return false }
	if a.RunAsNonRoot != nil {
		if *a.RunAsNonRoot != *b.RunAsNonRoot { return false }
	}
	if (a.ReadOnlyRootFilesystem == nil) != (b.ReadOnlyRootFilesystem == nil) { return false }
	if a.ReadOnlyRootFilesystem != nil {
		if *a.ReadOnlyRootFilesystem != *b.ReadOnlyRootFilesystem { return false }
	}
	if (a.AllowPrivilegeEscalation == nil) != (b.AllowPrivilegeEscalation == nil) { return false }
	if a.AllowPrivilegeEscalation != nil {
		if *a.AllowPrivilegeEscalation != *b.AllowPrivilegeEscalation { return false }
	}
	if (a.ProcMount == nil) != (b.ProcMount == nil) { return false }
	if a.ProcMount != nil {
		if *a.ProcMount != *b.ProcMount { return false }
	}
	if (a.SeccompProfile == nil) != (b.SeccompProfile == nil) { return false }
	if a.SeccompProfile != nil {
		if !SeccompProfileEqual(*a.SeccompProfile, *b.SeccompProfile) { return false }
	}
	if (a.AppArmorProfile == nil) != (b.AppArmorProfile == nil) { return false }
	if a.AppArmorProfile != nil {
		if !AppArmorProfileEqual(*a.AppArmorProfile, *b.AppArmorProfile) { return false }
	}
	return true
}

func SELinuxOptionsEqual(a, b corev1.SELinuxOptions) bool {
	if a.User != b.User { return false }
	if a.Role != b.Role { return false }
	if a.Type != b.Type { return false }
	if a.Level != b.Level { return false }
	return true
}

func WindowsSecurityContextOptionsEqual(a, b corev1.WindowsSecurityContextOptions) bool {
	if (a.GMSACredentialSpecName == nil) != (b.GMSACredentialSpecName == nil) { return false }
	if a.GMSACredentialSpecName != nil {
		if *a.GMSACredentialSpecName != *b.GMSACredentialSpecName { return false }
	}
	if (a.GMSACredentialSpec == nil) != (b.GMSACredentialSpec == nil) { return false }
	if a.GMSACredentialSpec != nil {
		if *a.GMSACredentialSpec != *b.GMSACredentialSpec { return false }
	}
	if (a.RunAsUserName == nil) != (b.RunAsUserName == nil) { return false }
	if a.RunAsUserName != nil {
		if *a.RunAsUserName != *b.RunAsUserName { return false }
	}
	if (a.HostProcess == nil) != (b.HostProcess == nil) { return false }
	if a.HostProcess != nil {
		if *a.HostProcess != *b.HostProcess { return false }
	}
	return true
}

func SysctlEqual(a, b corev1.Sysctl) bool {
	if a.Name != b.Name { return false }
	if a.Value != b.Value { return false }
	return true
}

func SeccompProfileEqual(a, b corev1.SeccompProfile) bool {
	if a.Type != b.Type { return false }
	if (a.LocalhostProfile == nil) != (b.LocalhostProfile == nil) { return false }
	if a.LocalhostProfile != nil {
		if *a.LocalhostProfile != *b.LocalhostProfile { return false }
	}
	return true
}

func AppArmorProfileEqual(a, b corev1.AppArmorProfile) bool {
	if a.Type != b.Type { return false }
	if (a.LocalhostProfile == nil) != (b.LocalhostProfile == nil) { return false }
	if a.LocalhostProfile != nil {
		if *a.LocalhostProfile != *b.LocalhostProfile { return false }
	}
	return true
}

func NodeAffinityEqual(a, b corev1.NodeAffinity) bool {
	if (a.RequiredDuringSchedulingIgnoredDuringExecution == nil) != (b.RequiredDuringSchedulingIgnoredDuringExecution == nil) { return false }
	if a.RequiredDuringSchedulingIgnoredDuringExecution != nil {
		if !NodeSelectorEqual(*a.RequiredDuringSchedulingIgnoredDuringExecution, *b.RequiredDuringSchedulingIgnoredDuringExecution) { return false }
	}
	if len(a.PreferredDuringSchedulingIgnoredDuringExecution) != len(b.PreferredDuringSchedulingIgnoredDuringExecution) { return false }
	for i := range a.PreferredDuringSchedulingIgnoredDuringExecution {
		if !PreferredSchedulingTermEqual(a.PreferredDuringSchedulingIgnoredDuringExecution[i], b.PreferredDuringSchedulingIgnoredDuringExecution[i]) { return false }
	}
	return true
}

func PodAffinityEqual(a, b corev1.PodAffinity) bool {
	if len(a.RequiredDuringSchedulingIgnoredDuringExecution) != len(b.RequiredDuringSchedulingIgnoredDuringExecution) { return false }
	for i := range a.RequiredDuringSchedulingIgnoredDuringExecution {
		if !PodAffinityTermEqual(a.RequiredDuringSchedulingIgnoredDuringExecution[i], b.RequiredDuringSchedulingIgnoredDuringExecution[i]) { return false }
	}
	if len(a.PreferredDuringSchedulingIgnoredDuringExecution) != len(b.PreferredDuringSchedulingIgnoredDuringExecution) { return false }
	for i := range a.PreferredDuringSchedulingIgnoredDuringExecution {
		if !WeightedPodAffinityTermEqual(a.PreferredDuringSchedulingIgnoredDuringExecution[i], b.PreferredDuringSchedulingIgnoredDuringExecution[i]) { return false }
	}
	return true
}

func PodAntiAffinityEqual(a, b corev1.PodAntiAffinity) bool {
	if len(a.RequiredDuringSchedulingIgnoredDuringExecution) != len(b.RequiredDuringSchedulingIgnoredDuringExecution) { return false }
	for i := range a.RequiredDuringSchedulingIgnoredDuringExecution {
		if !PodAffinityTermEqual(a.RequiredDuringSchedulingIgnoredDuringExecution[i], b.RequiredDuringSchedulingIgnoredDuringExecution[i]) { return false }
	}
	if len(a.PreferredDuringSchedulingIgnoredDuringExecution) != len(b.PreferredDuringSchedulingIgnoredDuringExecution) { return false }
	for i := range a.PreferredDuringSchedulingIgnoredDuringExecution {
		if !WeightedPodAffinityTermEqual(a.PreferredDuringSchedulingIgnoredDuringExecution[i], b.PreferredDuringSchedulingIgnoredDuringExecution[i]) { return false }
	}
	return true
}

func PodDNSConfigOptionEqual(a, b corev1.PodDNSConfigOption) bool {
	if a.Name != b.Name { return false }
	if (a.Value == nil) != (b.Value == nil) { return false }
	if a.Value != nil {
		if *a.Value != *b.Value { return false }
	}
	return true
}

func ResourceClaimEqual(a, b corev1.ResourceClaim) bool {
	if a.Name != b.Name { return false }
	if a.Request != b.Request { return false }
	return true
}

func ConfigMapEnvSourceEqual(a, b corev1.ConfigMapEnvSource) bool {
	if (a.Optional == nil) != (b.Optional == nil) { return false }
	if a.Optional != nil {
		if *a.Optional != *b.Optional { return false }
	}
	return true
}

func SecretEnvSourceEqual(a, b corev1.SecretEnvSource) bool {
	if (a.Optional == nil) != (b.Optional == nil) { return false }
	if a.Optional != nil {
		if *a.Optional != *b.Optional { return false }
	}
	return true
}

func EnvVarSourceEqual(a, b corev1.EnvVarSource) bool {
	if (a.FieldRef == nil) != (b.FieldRef == nil) { return false }
	if a.FieldRef != nil {
		if !ObjectFieldSelectorEqual(*a.FieldRef, *b.FieldRef) { return false }
	}
	if (a.ResourceFieldRef == nil) != (b.ResourceFieldRef == nil) { return false }
	if a.ResourceFieldRef != nil {
		if !ResourceFieldSelectorEqual(*a.ResourceFieldRef, *b.ResourceFieldRef) { return false }
	}
	if (a.ConfigMapKeyRef == nil) != (b.ConfigMapKeyRef == nil) { return false }
	if a.ConfigMapKeyRef != nil {
		if !ConfigMapKeySelectorEqual(*a.ConfigMapKeyRef, *b.ConfigMapKeyRef) { return false }
	}
	if (a.SecretKeyRef == nil) != (b.SecretKeyRef == nil) { return false }
	if a.SecretKeyRef != nil {
		if !SecretKeySelectorEqual(*a.SecretKeyRef, *b.SecretKeyRef) { return false }
	}
	if (a.FileKeyRef == nil) != (b.FileKeyRef == nil) { return false }
	if a.FileKeyRef != nil {
		if !FileKeySelectorEqual(*a.FileKeyRef, *b.FileKeyRef) { return false }
	}
	return true
}

func ContainerRestartRuleOnExitCodesEqual(a, b corev1.ContainerRestartRuleOnExitCodes) bool {
	if a.Operator != b.Operator { return false }
	if len(a.Values) != len(b.Values) { return false }
	for i := range a.Values {
		if a.Values[i] != b.Values[i] { return false }
	}
	return true
}

func LifecycleHandlerEqual(a, b corev1.LifecycleHandler) bool {
	if (a.Exec == nil) != (b.Exec == nil) { return false }
	if a.Exec != nil {
		if !ExecActionEqual(*a.Exec, *b.Exec) { return false }
	}
	if (a.HTTPGet == nil) != (b.HTTPGet == nil) { return false }
	if a.HTTPGet != nil {
		if !HTTPGetActionEqual(*a.HTTPGet, *b.HTTPGet) { return false }
	}
	if (a.TCPSocket == nil) != (b.TCPSocket == nil) { return false }
	if a.TCPSocket != nil {
		if !TCPSocketActionEqual(*a.TCPSocket, *b.TCPSocket) { return false }
	}
	if (a.Sleep == nil) != (b.Sleep == nil) { return false }
	if a.Sleep != nil {
		if !SleepActionEqual(*a.Sleep, *b.Sleep) { return false }
	}
	return true
}

func CapabilitiesEqual(a, b corev1.Capabilities) bool {
	if len(a.Add) != len(b.Add) { return false }
	for i := range a.Add {
		if a.Add[i] != b.Add[i] { return false }
	}
	if len(a.Drop) != len(b.Drop) { return false }
	for i := range a.Drop {
		if a.Drop[i] != b.Drop[i] { return false }
	}
	return true
}

func NodeSelectorEqual(a, b corev1.NodeSelector) bool {
	if len(a.NodeSelectorTerms) != len(b.NodeSelectorTerms) { return false }
	for i := range a.NodeSelectorTerms {
		if !NodeSelectorTermEqual(a.NodeSelectorTerms[i], b.NodeSelectorTerms[i]) { return false }
	}
	return true
}

func PreferredSchedulingTermEqual(a, b corev1.PreferredSchedulingTerm) bool {
	if a.Weight != b.Weight { return false }
	if !NodeSelectorTermEqual(a.Preference, b.Preference) { return false }
	return true
}

func PodAffinityTermEqual(a, b corev1.PodAffinityTerm) bool {
	if (a.LabelSelector == nil) != (b.LabelSelector == nil) { return false }
	if a.LabelSelector != nil {
		if !reflect.DeepEqual(*a.LabelSelector, *b.LabelSelector) { return false }
	}
	if len(a.Namespaces) != len(b.Namespaces) { return false }
	for i := range a.Namespaces {
		if a.Namespaces[i] != b.Namespaces[i] { return false }
	}
	if a.TopologyKey != b.TopologyKey { return false }
	if (a.NamespaceSelector == nil) != (b.NamespaceSelector == nil) { return false }
	if a.NamespaceSelector != nil {
		if !reflect.DeepEqual(*a.NamespaceSelector, *b.NamespaceSelector) { return false }
	}
	if len(a.MatchLabelKeys) != len(b.MatchLabelKeys) { return false }
	for i := range a.MatchLabelKeys {
		if a.MatchLabelKeys[i] != b.MatchLabelKeys[i] { return false }
	}
	if len(a.MismatchLabelKeys) != len(b.MismatchLabelKeys) { return false }
	for i := range a.MismatchLabelKeys {
		if a.MismatchLabelKeys[i] != b.MismatchLabelKeys[i] { return false }
	}
	return true
}

func WeightedPodAffinityTermEqual(a, b corev1.WeightedPodAffinityTerm) bool {
	if a.Weight != b.Weight { return false }
	if !PodAffinityTermEqual(a.PodAffinityTerm, b.PodAffinityTerm) { return false }
	return true
}

func ObjectFieldSelectorEqual(a, b corev1.ObjectFieldSelector) bool {
	if a.APIVersion != b.APIVersion { return false }
	if a.FieldPath != b.FieldPath { return false }
	return true
}

func ResourceFieldSelectorEqual(a, b corev1.ResourceFieldSelector) bool {
	if a.ContainerName != b.ContainerName { return false }
	if a.Resource != b.Resource { return false }
	if !a.Divisor.Equal(b.Divisor) { return false }
	return true
}

func ConfigMapKeySelectorEqual(a, b corev1.ConfigMapKeySelector) bool {
	if a.Key != b.Key { return false }
	if (a.Optional == nil) != (b.Optional == nil) { return false }
	if a.Optional != nil {
		if *a.Optional != *b.Optional { return false }
	}
	return true
}

func SecretKeySelectorEqual(a, b corev1.SecretKeySelector) bool {
	if a.Key != b.Key { return false }
	if (a.Optional == nil) != (b.Optional == nil) { return false }
	if a.Optional != nil {
		if *a.Optional != *b.Optional { return false }
	}
	return true
}

func FileKeySelectorEqual(a, b corev1.FileKeySelector) bool {
	if a.VolumeName != b.VolumeName { return false }
	if a.Path != b.Path { return false }
	if a.Key != b.Key { return false }
	if (a.Optional == nil) != (b.Optional == nil) { return false }
	if a.Optional != nil {
		if *a.Optional != *b.Optional { return false }
	}
	return true
}

func ExecActionEqual(a, b corev1.ExecAction) bool {
	if len(a.Command) != len(b.Command) { return false }
	for i := range a.Command {
		if a.Command[i] != b.Command[i] { return false }
	}
	return true
}

func HTTPGetActionEqual(a, b corev1.HTTPGetAction) bool {
	if a.Path != b.Path { return false }
	if a.Port != b.Port { return false }
	if a.Host != b.Host { return false }
	if a.Scheme != b.Scheme { return false }
	if len(a.HTTPHeaders) != len(b.HTTPHeaders) { return false }
	for i := range a.HTTPHeaders {
		if !HTTPHeaderEqual(a.HTTPHeaders[i], b.HTTPHeaders[i]) { return false }
	}
	return true
}

func TCPSocketActionEqual(a, b corev1.TCPSocketAction) bool {
	if a.Port != b.Port { return false }
	if a.Host != b.Host { return false }
	return true
}

func SleepActionEqual(a, b corev1.SleepAction) bool {
	if a.Seconds != b.Seconds { return false }
	return true
}

func NodeSelectorTermEqual(a, b corev1.NodeSelectorTerm) bool {
	if len(a.MatchExpressions) != len(b.MatchExpressions) { return false }
	for i := range a.MatchExpressions {
		if !NodeSelectorRequirementEqual(a.MatchExpressions[i], b.MatchExpressions[i]) { return false }
	}
	if len(a.MatchFields) != len(b.MatchFields) { return false }
	for i := range a.MatchFields {
		if !NodeSelectorRequirementEqual(a.MatchFields[i], b.MatchFields[i]) { return false }
	}
	return true
}

func HTTPHeaderEqual(a, b corev1.HTTPHeader) bool {
	if a.Name != b.Name { return false }
	if a.Value != b.Value { return false }
	return true
}

func NodeSelectorRequirementEqual(a, b corev1.NodeSelectorRequirement) bool {
	if a.Key != b.Key { return false }
	if a.Operator != b.Operator { return false }
	if len(a.Values) != len(b.Values) { return false }
	for i := range a.Values {
		if a.Values[i] != b.Values[i] { return false }
	}
	return true
}
